### ISSUE TITLE
Phone numbers do not properly discount when quoted with services

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#111]
**Describe the bug**
If a phone number and services are quoted through acceleratenetworks.com, two quotes are generated (which is perfect) but none of the fees for the phone numbers are discounted on the up front/one time quote.

**Comment by uncheckederror** [comment]
@danry25 Yep, that is correct and by design. We only discount Ported Phone numbers. From $20 to $0 for each service they purchased and $2 per ported number after that. If they don't purchase any services then ported numbers are $20 a piece. There are no discounts on numbers that we have to purchase from our vendors.
