### ISSUE TITLE
Add a mission statement to the About page

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#120]
Per our discussion earlier today we need to add a clear mission statement to the About page on our website.

@kylek206 and @scottstrong206 had some good thoughts on this issue.

Right now the mission statement is the first panel in the "Our Story" section.

> Our mission is to be the best communications provider a client could ask for, with flexible systems, reasonable prices and dependable support.

Ideally we would break this out into a separate section and then add some more content to the our story section.

We also need to get more headshots and descriptions up on this page to give customers confidence in our staff.

**Comment by uncheckederror** [comment]
@scottstrong206 how's the mission statement coming along?

**Comment by scottstrong206** [comment]
I’m going to send some options to the group later today. 

Sincerely,
Scott Strong
Director of Sales
206-408-3008 (call/text)
 (http://acceleratenetworks.com)

December 11, 2020 11:02 AM, "Thomas Ryan" <notifications@github.com (mailto:notifications@github.com?to=%22Thomas%20Ryan%22%20<notifications@github.com>)> wrote:
	@scottstrong206 (https://github.com/scottstrong206) how's the mission statement coming along?

**Comment by danry25** [comment]
@scottstrong206 Any progress on this?

**Comment by scottstrong206** [comment]
**About Us:**

Dan, Scott, Kyle, and Tom all graduated from Ballard High School right here in Seattle, Washington. Accelerate Networks was established in 2015 to give business owners a better solution for phone service. We understood the frustrations companies felt with ineffective technology, skyrocketing prices, and lackluster customer support. Our team saw an opportunity to better serve clients and to help them succeed with better a solution.
Not only are we committed to serving clients in the northwest and across the country, but we are just as committed to doing our part in the community. Kyle and Scott both are passionate members of the Ballard Rotary Club and spent many weekends helping on local projects. Accelerate Networks is also members of other community organizations like the Queen Anne Chamber of Commerce, Edmonds Chamber, Seattle Chamber, and the GSBA. 
We are immensely proud of our EnviroStars Tier 3 recognition for being a business that takes action to stay green! We often deploy refurbished phones, eliminate plastic waste, and partnered with local electronic recyclers to properly dispose of old equipment. 
In the telecommunications industry monthly charges are often confusing are hard to understand. People will read their bill and read things like “regulatory cost recovery fee” or “voice network investment fee”, what does that mean? 
Accelerate Networks core values are being honest, transparent, and having integrity. We do not hide fee(s) or raise prices two months down the road. The only additional cost beyond service with us is just e911 connectivity. 
When you decide to upgrade your phone system to Accelerate Networks you will be investing in your business with the most advanced telecom technology in the industry. Since the pandemic we have helped many businesses transition to working at home. We act as an advocate for our clients to ensure they have a reliable network, highspeed internet, and cable TV if needed.   
Over the intervening years we have come to serve grocers, law practices, dentists, doctors and plumbers across the region, while also contributing to the Free Software community by writing patches and documentation for the projects we use internally.
Give us a call and get to know our team!
Remember – If the ball is at the 1-yard line in the Superbowl … RUN the ball!
If you need great phone service for your business… call Accelerate Networks!

**Comment by scottstrong206** [comment]
Mission Statement:
To Accelerate businesses by delivering reliable phone systems, flexibility, reasonably low-cost, and friendly customer support.

**Comment by danry25** [comment]
I have done a first pass edit of this @scottstrong206, but I would like the input of @Chattaeus, @uncheckederror and @kylek206 too.

To view the original version of your comments, click on the dropdown arrow in the top bar of each comment to see the various versions of the About Us and Mission Statement.

**Comment by uncheckederror** [comment]
This content is live: https://acceleratenetworks.com/Home/About
