### ISSUE TITLE
Website Sequential Number Buy Option

### ISSUE THREAD

**Issue by Chattaeus** [AccelerateNetworks/NumberSearch#124]
The website should have a feature where you can buy a block of numbers. If I need 20 numbers and am not picky just click "add x numbers to cart" and checkout rather than going through one by one. I'm not a Foo Fighter, I want to buy a bunch of numbers quickly.

Alternatively if I am picky I should have the option to buy a block of sequential numbers. Maybe have a search option for "blocks" where it will show any and only groups of 2+ sequential numbers available within that area code. An option to select a minimum number of sequential numbers would be cool too, so if I need 7 numbers I can search blocks of 7 or more sequential numbers so all my numbers are in order.

Since I know Tom likes to charge more maybe put a convenience fee on the lazy option, IDK like $5 and charge extra per sequential number we add. We can work out the price later but maybe 2 sequential is and extra $20 then 3 is $30 then 4 is $40 on top of the cost of the numbers being bought.

**Comment by uncheckederror** [comment]
@danry25 interesting ideas here...

**Comment by danry25** [comment]
When Sequential is selected, there should be a visual indicator running through each group of consecutive numbers. Perhaps clicking on this should add the group of consecutive numbers to cart.

Here are some mockups:
![Screenshot from 2020-11-28 00-39-11](https://user-images.githubusercontent.com/1683673/100497998-ef11e880-3113-11eb-9ed6-82b2d102e2df.png)
![Screenshot from 2020-11-26 14-19-08](https://user-images.githubusercontent.com/1683673/100497999-efaa7f00-3113-11eb-8e07-904ee5107eec.png)

**Comment by uncheckederror** [comment]
I think there's a way to do this with a look ahead loop, but this is not an easy problem to mark out the groups, with start and end points as we render them out.

**Comment by uncheckederror** [comment]
The reason why we make you click the "Add to Cart" button for each number is because when you click that button we immediately verify that the number is still purchasable. 

As an example let's say that you wanted to purchase 40 numbers. We used to verify that each of these numbers was still available for purchase when you submitted your cart at checkout. But this lead to many problems like not being able to inform the user that something went wrong and the page timing out because running the queries for each number was taking too long.

Instead we now run this availability check when you click the add to cart button, so that you can be informed immediately if the number is no longer available and so that your order doesn't break when you submit your cart at the end.

So features like the 3 proposed in this issue present a number of problems: primarily that we'll have to skip these availability checks otherwise the page will timeout. Additionally we'd have to return to the user a list of the numbers that failed and ask them if they'd like to continue. But what if the next batch of numbers they selected also had failures? What if there are no more numbers in our system to grab? I don't see way to add these features without significantly increasing complexity and creating an  unreliable process.

**Comment by uncheckederror** [comment]
If we can figure out how to make the availability checks nearly instant, then we can implement this feature. But given our current architecture with multiple vendors I don't see a good way to make this work.

**Comment by danry25** [comment]
Could this not be done with some frontend javascript that calls the same add to cart endpoint (limiting itself to calling say 5 or 10 numbers at a time)? Then there would be no architectural changes on the server side.

**Comment by uncheckederror** [comment]
This has come up a couple times, but you seem to believe that adding complexity to the website by creating an API (a whole separate app) and then adding JavaScript front-end will somehow be able to paper over the fact that our vendors are slow and unreliable. 

It's true that the solution you're proposing will not timeout the page load. But it also won't be any faster for the user than just clicking the add to cart button for each number.

If we owned these numbers that would be one thing, but we don't and we're only sort of borrowing them for a bit.

**Comment by danry25** [comment]
The goal is to make a simple user experience. Hitting the add to cart button a dozen times as your viewport gets bumped around the page (as a full page reload is forced) is not a good user experience. This is passable if you want to run our site without Javascript, but nearly all users will have Javascript.

Handling the [Add to cart](https://git.callpipe.com/btcphone/btcphone/-/blob/master/btcphone/static/js/cart.js#L1) and [Remove button presses](https://git.callpipe.com/btcphone/btcphone/-/blob/master/btcphone/static/js/cart.js#L61) without a page reload was something I implemented in the Python version of this app 4 years ago. This should not need a separate app, can a route that takes in a number and cart then responds with a pass/fail not be added to the existing MVC app?

**Comment by danry25** [comment]
@uncheckederror, to recap our discussion there are 3 topics contained in this issue:
- Buying a sequential block of numbers
- Buying a random group of numbers from an area code
- Not reloading the page when buying phone numbers

Further discussion on this issue will only be about **Buying a sequential block of numbers**, and not reloading the page when buying phone numbers will be broken out into a separate issue. Buying random numbers is a use case that we will ignore, as it will improve as we fix the other two issues.

You do not like the thought of adding a second endpoint that is async which Javascript would use to check if a number is still available as this would create two codepaths and add complexity (tokens and such) to the design. Going this route would take approximately a month of development time at the current rate.

**Comment by uncheckederror** [comment]
https://acceleratenetworks.com/Search?Query=512&View=Sequential&Page=1

**Comment by danry25** [comment]
Thanks @uncheckederror & @dunkeltron, it looks quite nice!
