### ISSUE TITLE
Trouble submitting port requests to BulkVS

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#143]
**Describe the bug**
In the Ops app when I try to submit either of the port requests for Nick to BulkVS, the port request does not get submitted to BulkVS.

**Expected behavior**
A new port request should be created, the Ops app should note the port request # and it should also be viewable in the BulkVS portal.

**Comment by uncheckederror** [comment]
When I attempted to reproduce this issue all 5 number were successfully submitted to BulkVS for porting.

![image](https://user-images.githubusercontent.com/11726956/106841677-6b1a3680-6657-11eb-8b6b-12838b5e3bde.png)

**Comment by uncheckederror** [comment]
Upon thinking about this issue further it occurred to me that this is the only place in the Ops app where we're making a call to the BulkVS REST API, and that perhaps the credentials (username and password) weren't getting passed into the controller correctly. Similar problems have cropped up before.

I reviewed the appsettings.json file in the Ops app and found that the BulkVSUsername key was missing. I updated the file to resolve this oversight and redeployed the app through the pipeline. I then verified that all of the credentials are present on the production server.

@danry25 You'll have to run another port request through BulkVS to verify that this bug is now resolved.

**Comment by danry25** [comment]
@uncheckederror I am experiencing this again with the most recent port request for Nick that has 1 phone number associated.

**Comment by uncheckederror** [comment]
I've found a bug where the error messages were getting suppressed from the UI and the log.

**Comment by danry25** [comment]
Ok, let me know when the fix is pushed to production and I will retest!

**Comment by danry25** [comment]
I retested and the following error was generated:

```
 Failed to submit port request to BulkVS: Call failed with status code 409 (Conflict): PUT https://portal.bulkvs.com/api/v1.0/portTn at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response) at NumberSearch.DataAccess.BulkVS.PortTnRequest.PutAsync(String username, String password) in /home/vsts/work/1/s/NumberSearch.DataAccess/BulkVS/PortTn.cs:line 165 at NumberSearch.Ops.Controllers.HomeController.PortRequestSendToBulkVS(String OrderId) in /home/vsts/work/1/s/NumberSearch.Ops/Controllers/HomeController.cs:line 1083 
 ```

**Comment by uncheckederror** [comment]
I have updated the handling of failure messages from BulkVS to show them directly in the web app.

![image](https://user-images.githubusercontent.com/11726956/107285175-a334c700-6a13-11eb-859a-04f1c61d6407.png)

**Comment by danry25** [comment]
Cool, that is really helpful! Now I know to go bug the vendor since they screwed up and marked the number as being owned by us when it is still with the old provider.
