### ISSUE TITLE
Integrate New Client Worksheet into post-order flow

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#195]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
The new client worksheet gathers the customer requirements for their new phone system. Currently, salespeople forget to send this form, and clients often forget to fill it out until after our technician shows up on site (or the phones are shipped to them).

By moving this form to a webpage that the customer can fill out after placing their order, we make it easier for the client to provide us a description of their ideal phone system (rather than forcing them to muck about with filling out a PDF).

**Is your feature request related to a problem? Please describe.**
Customers fail to describe how they want their phone system to work since we aren't asking these questions at the time of order/quote generation on our website.

**Describe the solution you'd like**
Show the client a form similar to the Port Request page so they can assign their phones and extensions to users, describe how they want inbound calls to route, and what the purpose of their phone numbers actually is

**Describe alternatives you've considered**
We have been trying to use the form attached to get these customer requirements. When the customer is shown the form they do usually fill it out, but our delivery of this form is lacking.
[New Customer Worksheet.odt](https://github.com/AccelerateNetworks/NumberSearch/files/6706452/New.Customer.Worksheet.odt)

**Comment by uncheckederror** [comment]
Remaining work:

- [ ] Build API endpoints to perform CRUD operations on the five types of child items
- [ ] Add forms and JavaScript calls to the API endpoints for the child items

**Comment by danry25** [comment]
Awesome work @uncheckederror !

It would be nice if we could add dropdowns to Model of Phone and Outbound Caller ID:
![image](https://user-images.githubusercontent.com/1683673/134443685-e6dea1f2-126d-4a87-9682-41d7e8da742f.png)

**Model of Phone**
Show just a list of the phones ordered and quantity available and a More Phones button in the dropdown, and deduct from the quantity as they are assigned to extensions. If More is chosen, offer the full list of phones but show a warning in both Ops and on the worksheet that something odd happened.

For example, someone who ordered 3x GXP2170's and a Snom PA1 would see the following menu options:
When assigning the 1st extension a GXP2140: GXP2140 (3 available), Snom PA1 (1 available), More Phones
When assigning the 2st extension a GXP2140: GXP2140 (2 available), Snom PA1 (1 available), More Phones
When assigning the 3st extension a GXP2140: GXP2140 (1 available), Snom PA1 (1 available), More Phones
When assigning the 4st extension a Snom PA1: Snom PA1 (1 available), More Phones
When assigning the 5st extension a phone: More Phones

**Outbound Caller ID**
Show a dropdown of all phone numbers ordered, and an Other Number button that lets you enter a 10 digit numeric string.

Additionally, for the Phone Number/Description/Prefix dialog if we could make the Phone Number field have the same list of numbers as Outbound Caller ID along with an Other Number option, that would be helpful!

![image](https://user-images.githubusercontent.com/1683673/134444391-95283c0f-7475-46a0-9748-3b44498fe97c.png)
****

The question below should be broken into 4 yes or no questions rather than one omnibus question:
Do you use any **texting service**, **overhead paging** speakers, **intercom**, or have any **speed dial keys** you would like us to configure?

Use Yes or No toggles, show a text box and dependent questions (eg: all of the amplifier, intercom & speed dial questions) should only be shown when the user chooses Yes.

Please also restrict these form inputs to accept numbers only:
 - Extension (2 to 14 digit number)
 - Phone Number (10 digit number)
 - Extension making the call to Intercom (2 to 14 digit number)
 - Extension receiving the Intercom (2 to 14 digit number)
 - Phone Number/Extension Number (2 to 14 digit number)
 - Extension Number (2 to 14 digit number, drop the word Number)
 - Cell # for Follow Me (10 digit number)
 - Forward to # when unreachable (10 digit number)

**Comment by uncheckederror** [comment]
Removed the max length 10 constrain from the NameOrLocation at @danry25 request.

**Comment by danry25** [comment]
Related to #194 we need to not register a customer's phone number for SMS/MMS service with Teli ([here is the doc](https://apidocs.teleapi.net/api/offnet-provisioning/submit-number), set enable_sms to no)when boarding it as an offnet number if they select they use a texting service (ZipWhip, Podium, etc) for their phone numbers.

**Comment by uncheckederror** [comment]
@danry25 are we good on the checkboxes/toggles?

**Comment by danry25** [comment]
@uncheckederror Can we update the flavor text for the phone menu text box to "What would you like your menu to say? Eg: Thanks for calling Business Name, press 1 for..." and add a grid below to capture menu options and routing information (see picture below).
![Screenshot from 2021-11-24 09-31-27](https://user-images.githubusercontent.com/1683673/143287249-97e056ba-50dc-4b29-9499-d0c7b6cbea57.png)

Additional scope creep would be implementing Microsoft Text to Speech to take the contents of the main text box and turn it into a recording, ideally providing the user the choice of which voice to use but defaulting to Aria (neural): https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech/

**Comment by uncheckederror** [comment]
@danry25 this phone menu options feature is now live. Please try it out.

**Comment by danry25** [comment]
The phone menu defaults to No Phone Menu after I add a few menu options and reload the page without submitting the full form.

Can we make it so filling in any menu options or text about a phone menu causes this to select Phone Menu?
