### ISSUE TITLE
Failed to submit port request to BulkVS: Object reference

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#197]
**Describe the bug**
I get " Failed to submit port request to BulkVS: Object reference not set to an instance of an object. at NumberSearch.Ops.Controllers.HomeController.UnifiedPortRequestAsync(String OrderId) in /home/vsts/work/1/s/NumberSearch.Ops/Controllers/HomeController.cs:line 1582 " when trying to submit the most recent port request

**To Reproduce**
1. Go to ops.acceleratenetworks.com
2. Click on the most recent order that has 2 local phone numbers attached for a Woodinville business
3. Scroll down to Submit Port Request and press it

**Expected behavior**
A port request should be submitted to BulkVS. No new port request is showing on their side

**Screenshots**
![image](https://user-images.githubusercontent.com/1683673/123526075-5c75ff80-d68a-11eb-9195-39fc04cda010.png)

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox 78.10.0esr (64-bit)

**Comment by uncheckederror** [comment]
Not sure what happened here, I tried to reproduce this error but the Port Request was accepted by BulkVS. You can verify that the two numbers have been submitted by looking at the order in the Ops app. I have added additional logging to capture the responses from BulkVS.

Line 1582 is where the Address is parsed into the format that BulkVS expects so this could have broken because the Address associated with this port request was zero length or null.
