### ISSUE TITLE
504 Gateway Timeout on large number ports

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#218]
**Describe the bug**
@takoyakiallenc encountered a 504 Gateway Timeout when trying to use our [Lookup/Port page](https://acceleratenetworks.com/Lookup) to port 89 phone numbers to us.

**To Reproduce**
1. Go to https://acceleratenetworks.com/Lookup
2. Enter 89 numbers into the field where it says "Enter Phone Numbers"
3. Press Transfer
4. See 504 Gateway Timeout error after 2 minutes

**Expected behavior**
The webpage should reload within a few seconds and allow portable numbers to be ported to us.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 91.0

**Additional context**
It seems every additional number added to the list adds ~1.3 seconds of processing time. If we could parallelize these queries (eg: Fire off the LRN, CNAM & portability queries at the same time) and parallelize our sending of these queries for each phone number, hopefully we can cut down this linear scaling?

I will benchmark the various APIs we hit and update this thread if I find any easy optimizations.

**Comment by TakoyakiAllenC** [comment]
Hi. It won't even handle 50 numbers. I dropped it to 30 to make progress. TTL of packets die way before it can finish. Browser thinks the server becomes unresponsive. I deploy 100+ numbers easily so this system needs to be far easier to work with.

I hate using this portal. Please make me unhate it.
Thanks.

**Comment by uncheckederror** [comment]
I have updated the code that supports the Bulk Phone Numbers page to handle a group of 50 numbers (as a benchmark) in slightly less than 8 seconds. I need to conduct additional performance testing to see where we're at on the production server, rather than just my local machine. 

I believe there is way we could architect this process to scale to n(ish) numbers, but there are a couple of fundamental limitations at play here. The customer's browser will time out the request, is the biggest one in my mind.

We need this process to be as fast as possible, so as not to annoy the customer. As a minimum we need this process to timeout. 

Why does this process take so long? For each number we check with 3 different HTTP APIs to gather information about the number that was submitted. 

- BulkVS requires ~0.5 seconds per number (stable performance per number)
- Teli requires ~1.5 seconds per number (performance declines as additional number are added)
- Data24/7 requires ~5 seconds per number (performance declines as additional number are added)

I have sped things up by running all of the numbers submitted through this process at the same time. This helps hide some of the latency of the slowest API requests and allows to server to continue doing meaningful work while it waits for responses from the 3rd party APIs. 

But there is still some upper limit to what this page can handle in terms of the numbers submitted. I intend to figure this limit out through testing so that we can rewrite the flavor text to better set the customer's performance expectations.

**Comment by uncheckederror** [comment]
Here's a perf example from Chrome with the new process, where 50 numbers are handled in ~8 seconds.

![image](https://user-images.githubusercontent.com/11726956/130314169-bf926125-8413-47db-bfb0-596ebb950ad9.png)

**Comment by TakoyakiAllenC** [comment]
Given what little knowledge I know of http requests, you could submit a keep alive signal back to the browser. There are many platforms that offer a loading graphic to indicate a query takes more time than allows for a typical ttl. It's OK to take longer if you really need it but keep the client side alive rather than going to timeout error.

I can easily submit clients with 150 numbers to port at once and we will definitely hit a timeout even with this performance. It's good design to simply show what numbers you do get a response for with a loading bar for numbers that need more time to process.

**Comment by danry25** [comment]
@uncheckederror For the Teli API, have we tried [their bulk portability check endpoint](https://apidocs.teleapi.net/api/lnp-portability/check-number-portability-bulk)? This will reduce the problem from many small queries to a single query to them, where they have access to the LRN & LATA data at much lower latency than we do.

Essentially, all Teli is doing is checking if the LATA (the local area the phone number is in) is marked as portable to one of the carriers they partner with.

For Data24/7, if their performance is unstable lets dump their endpoint for the BulkVS CNAM or Teli CNAM endpoint. I will update this comment with those shortly.

**Comment by uncheckederror** [comment]
@TakoyakiAllenC Okay, thanks for the info on the batch size. 50 numbers is obviously too small. I will find a list of 200 phone numbers to test performance of this process, hopefully we can good idea of where we stand using that.

**Comment by TakoyakiAllenC** [comment]
You're eventually going to hit a wall on your dependencies and even network lag. You don't want your performance to be set only at low peak hours like midnight. Many times we work in higher congestion environments. I still think the design needs to change per my comments here: https://github.com/AccelerateNetworks/NumberSearch/issues/218#issuecomment-903075758

**Comment by danry25** [comment]
@TakoyakiAllenC We may eventually hit a wall with performance from the CNAM and LRN endpoints for our vendors, but I am not too worried throwing 500 queries at these endpoints at any given time given that we already hit them dozens to hundreds of times a minute, and other clients of these vendors are doing hundreds of queries a second at peak times as the they set up incoming and outgoing calls.

**Comment by uncheckederror** [comment]
On the live production website:

200 numbers took 15 seconds.
![image](https://user-images.githubusercontent.com/11726956/130337798-5411d655-2276-454e-a4d5-845ba79435c0.png)

250 numbers took 18 seconds.
![image](https://user-images.githubusercontent.com/11726956/130337825-3f5295ef-df90-438e-9a63-d21e9040b511.png)

260 numbers took 12 seconds.
![image](https://user-images.githubusercontent.com/11726956/130337865-68831f22-cdf0-4c65-b2f6-5570a8fe3ded.png)

300, 275, and 265 numbers instantly failed out.

**Comment by danry25** [comment]
@uncheckederror, the NPA-555 block is usually purposefully reserved/invalid [like 206-555 is](https://www.telcodata.us/search-area-code-exchange-detail?npa=206&exchange=555), while [the 525-374 block is unassigned](https://www.telcodata.us/search-area-code-exchange-detail?npa=525&exchange=374) and 8886409088 is returning "Invalid: (888) 640-9088 Existing port request" causing it to fail.

I will retest with a large quantity of valid numbers soon and update this comment.

**Comment by uncheckederror** [comment]
@danry25 I have implemented the Teli bulk portability checking endpoint in 0913f9a and the new build is live on the website for performance testing.

**Comment by danry25** [comment]
I am seeing the Lookups page respond in 6 to 12 seconds when 352 numbers are queried. Given that we now state a 200 number limit for the Bulk tool, I believe this is sufficiently performant and has a large enough safety margin to leave as is.

Thanks for the massive performance improvement @uncheckederror!
