### ISSUE TITLE
After completing ingest of new phone numbers, attempt to add the numbers to cart

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#270]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
This should catch more unsellable numbers and remove them from our database proactively, reducing customer frustration with the website.

**Describe the solution you'd like**
After completing ingest of new phone numbers, attempt to add the numbers to cart to verify they are still available.

**Comment by uncheckederror** [comment]
This bug was actually cause by the dids/list?token=&search= API call reporting success but never returning any results. I have solved this issue by replacing this API call with dids/list?token=&npa=&nxx in all the places where it was being used to verify the existence of a single phone number.

Additionally I have updated the ingest app to verify that all of the Executive numbers in priority area codes can be added to the cart everytime a priority ingest is run.
