### ISSUE TITLE
Update home page with an active background

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#31]
We created some marketing videos in early 2020 that are in Nextcloud (shared with @uncheckederror), perhaps we could make the homepage default to rolling through those and push the current carousel of phones further down the page?

Likely need to convert the videos to webm, gifv or some other web friendly format...

**Comment by uncheckederror** [comment]
If we're going to use this video to loop as the background on the website we need a tighter edit.

The first 20 seconds could be dropped. The first frame needs to contain the accelerate networks logo.

This background video is a hard sales pitch that needs to communicate two things to the viewer: Accelerate Networks and desk phones. Every shot in the video should contain either a the logo or a phone. 

Ideally the run time should be about 30 seconds and due to the layout issues on the web rather than using a 16:9 aspect ratio we should go for 21:9 so the video doesn't eat up the whole page on normal PC monitors.

Here's what it looks like in the web layout on normal monitors:

![image](https://user-images.githubusercontent.com/11726956/81464695-c2e34a00-9178-11ea-8982-d2c141bb2f72.png)

If we used a wider aspect ratio we could have a smaller vertical height and get more of the sales text on the page.

**Comment by uncheckederror** [comment]
This change with the 21:9 video has been committed.

**Comment by uncheckederror** [comment]
This has been deployed to the public website.
