### ISSUE TITLE
Blog broke formatting for recent post "How Do I…?"

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/NumberSearch#315]
# Describe the bug
Formatting seems to be fine on blog.acceleratenetworks.com but is broken on acceleratenetworks.com/blog

# Screenshots
<img width="708" alt="Screenshot 2023-02-17 at 4 51 25 PM" src="https://user-images.githubusercontent.com/44306072/219822580-3d571f24-03c1-4bc0-a32a-b456e8e0733b.png">
https://blog.acceleratenetworks.com/
<img width="759" alt="Screenshot 2023-02-17 at 4 51 34 PM" src="https://user-images.githubusercontent.com/44306072/219822597-e4aa332c-21f7-419d-b9f8-564f03f30e78.png">
https://acceleratenetworks.com/blog

# Seen on the following
Chrome on Windows 10
Firefox on Mac OS

**Comment by uncheckederror** [comment]
The write.as API is providing that section of the markdown file with a specific number of spaces to achieve the centering of the test. The markdown library is interpreting this as pre-formatted code block which why the styling and linking fails. Even if I could get the markdown to html conversion process to not see it as a code block the formatting would still be broken because space characters which are not consistent or responsive. Perhaps the simplest solution here is to not use that styling/centering mechanism in the write.as editor?
