### ISSUE TITLE
About page Feedback

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#338]
1. The "[About](https://acceleratenetworks.com/About)" page needs to start with “Our People” at the top of the page, then go into the Local Values, Community  Commitment, Customer Obsession, etc part. Either change the banner headline, or bring "Our People" up to the top of the about page to meet the expectations of the banner. 
2. Maskless headshots should be taken
3. Bios should be revamped
3a. How is Scott going to build me a solution? What skills does he have to make this happen? (Show it, don’t say it.)
3b. Quentin – tell me about his background in business development. Can you tell me about a time he pinpointed a production or budgeting issue? (People like statistics.)
3c. Dan should be moved up. He’s the boss. And get rid of the “accels at.” One, because excels is the word, and two, you don’t end a sentence in a preposition. Also, what is,“Github – danry25?” Why do some have telephone numbers and some have that?
3d. Thomas – can the “consulting” part of his title be removed? It makes it sound like he has another “real” job and this is a side gig. Change the word, “goal” to something else, like aim. Also, what is, “Github – uncheckederror?” I’d be consistent with phone numbers or Githubs.
3e. Hannah – Under “Director of Operations,” there’s a typo with “services.” Also, this needs a different headshot, with hair more in order. And “top tier customer support” should read, “top-tier customer support.” 
3f. Under "Our People -> Hannah, "It’s not really why you get up in the morning. No one will believe that. I don’t, and I’m your mom and want to believe it’s true. I’d say, “Hannah’s focus is on providing top-tier customer service, with a smile.”"
3g. Finn – change his picture. And “open source software”
4. Local Values
4a. Add the last names of each – and whether they’re related and how. It gives a personal feel – and also shows transparency.
4b. Why is the fact that they graduated from Ballard relevant. Did they form the company then? Did they graduate same year? Are they trying to reach the Bucky the Beaver demographic only? And if so, then rival high school grads may be disinclined to support their venture.
5. Community Commitment
5a.  I see Scott’s membership, but what about Dan and Tom – or any other members of the team? If it’s only Scott, then maybe remove his Rotary Club info. and focus instead on the organization’s memberships. 
5b. List out Greater Seattle Business Association. I don’t want to have to google the acronym to find out what it is if I don't already know what it is. 
6. Proven Success
6a. I would say instead, “Over the years, our customers include every range of work environment, from grocers to legal and medical, from plumbers to mechanics, across the nation. We also support the Free Software Community by writing patches and documentation.” I’m not sure about the “for the projects we use to serve our clients” part. That’s confusing to me.

**Comment by uncheckederror** [comment]
> 1. The "[About](https://acceleratenetworks.com/About)" page needs to start with “Our People” at the top of the page, then go into the Local Values, Community  Commitment, Customer Obsession, etc part. Either change the banner headline, or bring "Our People" up to the top of the about page to meet the expectations of the banner.

This page follows this flow: Values => Mission => People => Community. What is a banner headline that would set these expectations?

> 2. Maskless headshots should be taken

Is there a specific business justification to unmask our employees? Will maskless headshots reduce the cost of the services we provide or increase the value of the services we deliver?

> 3. Bios should be revamped
>    3a. How is Scott going to build me a solution? What skills does he have to make this happen? (Show it, don’t say it.)
>    3b. Quentin – tell me about his background in business development. Can you tell me about a time he pinpointed a production or budgeting issue? (People like statistics.)
>    3c. Dan should be moved up. He’s the boss. And get rid of the “accels at.” One, because excels is the word, and two, you don’t end a sentence in a preposition. Also, what is,“Github – danry25?” Why do some have telephone numbers and some have that?
>    3d. Thomas – can the “consulting” part of his title be removed? It makes it sound like he has another “real” job and this is a side gig. Change the word, “goal” to something else, like aim. Also, what is, “Github – uncheckederror?” I’d be consistent with phone numbers or Githubs.
>    3e. Hannah – Under “Director of Operations,” there’s a typo with “services.” Also, this needs a different headshot, with hair more in order. And “top tier customer support” should read, “top-tier customer support.”
>    3f. Under "Our People -> Hannah, "It’s not really why you get up in the morning. No one will believe that. I don’t, and I’m your mom and want to believe it’s true. I’d say, “Hannah’s focus is on providing top-tier customer service, with a smile.”"
>    3g. Finn – change his picture. And “open source software”
Finn will only provide this image.

This feedback brings up a good point though, which is the value of this flavor text. Does it actually add anything or should just remove it? On that same note does list phone numbers for the sales people and github links for support staff make sense? As in do we want people to contact us based off the information on this page. I'm not sure that we do, so perhaps we should also remove the contact information as we really only want our customers to call either the support number at the top of the page or that sales number on the home page or in the footer.

I think I'm favor of removing both the text and the contact info from the headshots because it will reduce the cost of maintaining this page and it avoids distracting the reader with info that's not relevant to funneling them into our sales pipeline.

> 4. Local Values
>    4a. Add the last names of each – and whether they’re related and how. It gives a personal feel – and also shows transparency.
>    4b. Why is the fact that they graduated from Ballard relevant. Did they form the company then? Did they graduate same year? Are they trying to reach the Bucky the Beaver demographic only? And if so, then rival high school grads may be disinclined to support their venture.
> 5. Community Commitment
>    5a.  I see Scott’s membership, but what about Dan and Tom – or any other members of the team? If it’s only Scott, then maybe remove his Rotary Club info. and focus instead on the organization’s memberships.
>    5b. List out Greater Seattle Business Association. I don’t want to have to google the acronym to find out what it is if I don't already know what it is.
> 6. Proven Success
>    6a. I would say instead, “Over the years, our customers include every range of work environment, from grocers to legal and medical, from plumbers to mechanics, across the nation. We also support the Free Software Community by writing patches and documentation.” I’m not sure about the “for the projects we use to serve our clients” part. That’s confusing to me.

Yeah I guess we need to decide what the purpose of this About page is. Is it a sales pitch? @scottstrong206 what are we trying to do here.

You can see the original discussion when Scott wrote our Values and Mission statement here: https://github.com/AccelerateNetworks/NumberSearch/issues/120

The team felt strongly at the time that we needed to get this content on the website in order to match with the content found on our competitor's websites. Perhaps we should work with the sales team to build this page into better funnel by rewriting our values as an argument to the customer on why they should pay for our services?

**Comment by uncheckederror** [comment]
![localhost_44316_About](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/c337e6ea-859d-4691-aa0a-fe4538a50b41)

I kinda like it in this simpler format for the headshots. In terms of the ordering of people I think we need prioritize headshots based on who we want customers to contact or call. To me that means the sales team first, then the support team, followed by the systems team. Although I would like to put Tyler and Thaddaeus on the about page neither of them have provided headshots.

**Comment by danry25** [comment]
Closing given no response by @sewcialite @scottstrong206 in the last two weeks. Please only open issues you intend to engage with @sewcialite @scottstrong206
