### ISSUE TITLE
attempting to update webhook URL for inbound SMSs to a particular number does not update

### ISSUE THREAD

**Issue by thefinn93** [AccelerateNetworks/NumberSearch#348]
I tried updating the callback URL and secret for one of my test numbers, and it seemed to work:

```
$ curl -id '{"dialedNumber": "12068589312", "callbackUrl": "https://april-12-finn-test.sip.callpipe.com/app/webtexting/providers/accelerate-networks.php", "clientSecret": "aaaa"}' -H "Authorization: Bearer ${token}" -H "Content-Type: application/json" https://sms.callpipe.com/client/register
HTTP/2 200 
server: nginx/1.18.0
date: Tue, 13 Jun 2023 18:56:32 GMT
content-type: application/json; charset=utf-8
x-content-type-options: nosniff

{"dialedNumber":"2068589312","callbackUrl":"https://april-12-finn-test.sip.callpipe.com/app/webtexting/providers/accelerate-networks.php","registered":true,"message":""}%                                                                                                                                                                                                 
```

but when I sent a text to that number I didn't receive a request to the URL. So I checked the client registration, and it did not update either the URL or the clientSecret

```
$ curl -sH "Authorization: Bearer ${token}" -H "Content-Type: application/json" https://sms.callpipe.com/client\?asDialed\=12068589312 | jq                                                                                                                                                         
{
  "clientRegistrationId": "dd270bfb-f3cc-4bae-9b66-44976d2959f3",
  "asDialed": "2068589312",
  "callbackUrl": "https://dev.home.finn.io/api/inbound/accelerate_networks",
  "dateRegistered": "2023-04-21T17:20:35.9585101",
  "clientSecret": "xxxxx"
}
```

**Comment by uncheckederror** [comment]
@thefinn93 To improve this situation I have expanded the success messages that you can receive from the POST /client/register endpoint. It will now directly tell you the status of the number you registered with the upstream vendor so that you don't have to look it up on your own. This info in the the 'Message' field of the JSON response ex:
```
{
  "dialedNumber": "2068589310",
  "callbackUrl": "https://sms.callpipe.com/message/forward/test/",
  "registered": true,
  "message": "This number is routed for SMS service with our upstream vendor: OK"
}
```

Where the 'OK' at the end is whatever text the vendor passed back to us when we asked if the number was SMS enabled and routed to us. If the number is not registered you will get a more complex response that should shed some light on why that number is not ready for SMS service from the vendor.

This updated build is now live and the registration updating bug is resolved. Please verify the fix.

**Comment by thefinn93** [comment]
Thank you, I'm sure that will be useful! 

Unfortunately, that is not what this ticket is about. I tried to re-register a number that is already SMS enabled (changing the callback URL), but it didn't update the stored registration URL.

**Comment by uncheckederror** [comment]
@thefinn93 
> This updated build is now live and the registration updating bug is resolved. Please verify the fix.

**Comment by thefinn93** [comment]
ahh thanks lol. Will verify in the morning.

**Comment by danry25** [comment]
@thefinn93 Bump, please review and close if this is resolved.
