### ISSUE TITLE
Drop support for purchasing numbers through Peerless

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#349]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**

Depreciating support for this vendor will spare us from spending staff time contacting their sales and support teams. It will also speed up the numbers ingest process and remove the burden of maintaining the code that implements this feature.

**Is your feature request related to a problem? Please describe.**
Peerless is an unreliable vendor that often has downtime and fails out requests for querying for and purchasing phone numbers. Lets skip around this by not doing it anymore.

**Describe the solution you'd like**
Drop support for Peerless.

**Describe alternatives you've considered**
Continuing to offer support for Peerless seems untenable due to the mismatch between the capabilities described by their sales team and the unreliability of the services delivered by their backend.

**Additional context**
Peerless support is included in both the Ingest and Mvc apps.

**Comment by uncheckederror** [comment]
@danry25 please verify that we're good on this.

**Comment by danry25** [comment]
Looks good, we have made no progress with Peerless Networks on peerlessnetwork.io account restoration or providing access to the endpoint that provides the NPA-NXXes they have inventory in (which would let us reduce our queries from 1000 per area code to a few dozen or less).

To recap we were only importing available numbers in Washington and Oregon area codes due to how slow the Peerless API was, hence why we scaled down to the dozen priority area codes many months ago. Then the Vice President, IT of Peerless's parent company Infobip bricked our API keys and portal access and said:
```
Accelerate Networks is placing more than 1 number search request per second via the Portal API. It seems to be happening in bursts ever hour or so. This was starting to impact downstream systems. Looks like they have some automated system that is looping through rate centers and searching for consecutive numbers. This is a misuse of the API. We have disabled their API key.

Can you please reach out to them to notify them that we have disabled their API key and see if you can find out what they were doing?"
```
I did make an effort with our prior two Peerless reps to advise of exactly what we were doing via API and our needs (a current list of in stock NPA-NXXes) and goals, but got zero traction. I also touched base with other former clients of Peerless that were at larger scale, they had similar experiences.

For my own reference, our disabled login for peerlessnetwork.io shows this error and password resets do not result in an email. Peerless Sales and support have been unresponsive via email.
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/6ad8bf43-db0d-423e-8db1-cef248eb36f9)
