### ISSUE TITLE
Number shows as porting in, but is already ported and routed

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#359]
**Describe the bug**
When I look at [4256443870](https://ops.acceleratenetworks.com/Home/OwnedNumbers/4256443870) it shows the number as Porting In, but we have served this phone number for years.

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/OwnedNumbers/4256443870
2. See error

**Expected behavior**
This phone number should show as active.

**Additional context**
[This order](https://ops.acceleratenetworks.com/Home/Order/20c5fc73-2331-4b89-bfaf-3ba52d7c5b83) is associated with 4256443870 but the order appears to be broken, likely causing this issue.

**Comment by uncheckederror** [comment]
@danry25 how do you know that 20c5fc73-2331-4b89-bfaf-3ba52d7c5b83 is associated with 4256443870?

What should the correct status be for this number?

**Comment by danry25** [comment]
This number should show as active, and I see order 20c5fc73-2331-4b89-bfaf-3ba52d7c5b83 is associated with 4256443870 as the top order from 8/26/2021 here:
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/38ebce21-1f07-40ee-a9f7-cea7de7403b6)

**Comment by uncheckederror** [comment]
Alright so there is no record of an order with that OrderId in the database. It's not just broken, it's gone or perhaps deleted at some point.

**Comment by danry25** [comment]
90% sure it got deleted at some point

**Comment by uncheckederror** [comment]
Yeah, so then perhaps the solution here is to delete this record for the ported dialed number?

**Comment by danry25** [comment]
Deleting the record for the ported dialed number that was created by the deleted order seems reasonable. When will the next owned numbers ingest run?

FYI I think we have other affected numbers by this bug like 5015292010 and 4259993188 @uncheckederror 

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/de61ebf4-452a-4043-8a62-e29ebd929809)

**Comment by uncheckederror** [comment]
@danry25 how do you tell when a number has this problem? The owned numbers ingest run every 6 hours.

**Comment by danry25** [comment]
I look to see if the number is active on BulkVS and meets one of the following conditions:
- If it has a port date that is similar to what Ops has on file and is on Onvoy or Bandwidth.com or another carrier we use
- Its routed in FusionPBX and has recent calls in the Call Detail Records

**Comment by uncheckederror** [comment]
> 5015292010 

Looks right to me, there is an incomplete port request associated with it where it has a status of "CANCELLED" from BulkVS.

> 4259993188 

Also looks right in that it has an order and a port request where Teli gave it a status of "rejected" before we quit ingesting data from Teli.

**Comment by danry25** [comment]
For the port for 5015292010 BulkVS LNP Order 1626870 shows as Completed:
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/ebf10ade-9a00-4965-9326-24a63f54e53b)

4259993188 ported over to BulkVS on order 1674471 (which shows up twice in BulkVS's portal, and probably via API too) coming from Teli. Its a former customer's number (the customer closed their business) that we ended up with.

**Comment by uncheckederror** [comment]
When we query Bulk VS for a list of our Port Requests through their REST API we get back a list that only goes until 5/5/2022. Port Requests that happened prior to that will not have their statuses updated, unless we directly query for them by the OrderId in BulkVS's system. This is why the status of port request for 5015292010 still shows as CANCELLED in our system; we are no longer updating it, because it's not provided in the list from BulkVS's API due to its age.

To get around this we could have a daily process for PortedNumbers and PortRequests with RequestStatus that are not COMPLETE where we query BulkVS for details on that requests using the external OrderId and then update the status from there. I think this would mark the port request as COMPLETE and then on the next Owned Numbers ingest the Status would get updated from "Porting In" to "Active".

**Comment by danry25** [comment]
Once the port request goes to Complete status we need to stop querying the BulkVS API for said port request.

If a phone number shows up on the BulkVS platform under Inbound Numbers with a status of Active, it should show as Active in Owned Numbers.

**Comment by uncheckederror** [comment]
> Once the port request goes to Complete status we need to stop querying the BulkVS API for said port request.

Yes, we already do this.

> If a phone number shows up on the BulkVS platform under Inbound Numbers with a status of Active, it should show as Active in Owned Numbers.

How do we query for those conditions?

**Comment by danry25** [comment]
We query for this using the Status parameter on a phone number when using this endpoint: https://portal.bulkvs.com/api/v1.0/documentation#/Origination/get_tnRecord

**Comment by uncheckederror** [comment]
When a number appears to be "Porting In" we check it's status with BulkVS using the get TNRecord endpoint, and if it has a Status of "Active" then we mark it as active in our system, otherwise we continue to mark it as "Porting In". All three of the numbers you mentioned in this issue now show as active Owned Numbers in Ops.
