### ISSUE TITLE
Ops - Orders Hidden

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#363]
**Describe the bug**
Under 100 orders are being shown to me in Ops

**Expected behavior**
Over 140 orders should be shown

**Additional context**
Sales tax calculation did not occur for the order on 7/5/2023 (which I am unable to view due to the orders hidden bug)

**Comment by uncheckederror** [comment]
@danry25 This fix is live now. It wasn't the 100 order limit that was breaking your view. Rather it was because you have both the Sales and Support roles inside of Ops and we were checking for just the Sales role to limit your view to orders where you were listed as the Sales rep. Now it also checks to see if you have the Support role and skips that filtering step.
