### ISSUE TITLE
[FEATURE] Expand the new Client worksheet

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#368]
Extend the new client worksheet to include
- [x] What is the client's router (Vendor, Model)
- [x] who their IT vendor is and how do we contact them
- [x] a picture of their networking cabinet

**Comment by sewcialite** [comment]
Super pedantry...Dan has asked customers be called clients. Can we change the button to say "Client's View"  instead? 

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/9c1077f2-6ea6-4797-a08e-2302d2434d9c)

**Comment by sewcialite** [comment]
Spelling Error of immediate: 

Please call [(206) 858-8757](tel:206-858-8757) for immediate help filling out this form. You can also email us at [support@acceleratenetworks.com](mailto:support@acceleratenetworks.com).

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/a98f9687-f637-417c-84d3-e468395702c5)

**Comment by sewcialite** [comment]
We should know what hardware they have because we installed or ordered it. No need for that field.

"Let’s get individual lines set up for your account. Do you have a list of any current extensions?

Does anyone need an extension without a phone (eg: Voicemail to email or Mobile/PC app only)?" 

Bolded  above Text Entry Fields:  Extension Number / Name or Location / Email (Voicemail Notifications) / Outbound Caller ID
Placeholder Text: eg; 101 / eg: John Doe or Back Office / optional / eg: Business # or Direct # 

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/f0c0a4b3-cb8c-487b-bd44-3a038f8437ca)

**Comment by sewcialite** [comment]
This placeholder text has some odd spacing in it. 

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/b8fd5fae-4607-47b9-8b50-46bcbcf8fe78)

**Comment by danry25** [comment]
Changes:
- Move Your Internet Connection to New Client Form
- Create Toggle for Am I under contract (Yes/No/Unknown) to hide Contract Date and Term fields
- Ask for current bill/contract (provide attach file button)
- Link to Speedtest.net and ask for them to paste their result in

**Comment by uncheckederror** [comment]
@danry25 @sewcialite these changes are live now. Please try it out and provide your feedback here.

**Comment by danry25** [comment]
Could we change both references to "is the client" to not reference the client in 3rd person?

Eg:  "What router do you use? Include the manufacturer's name and the model number of the router." and " Who does your IT? Is there a consistent person you work with at said vendor (name, email & phone #)

**Comment by uncheckederror** [comment]
@danry25 your feedback is live.

**Comment by sewcialite** [comment]
Looks great to me! I agree with Dan more work is needed by support for a script than continued effort on the form

**Comment by uncheckederror** [comment]
Closing as we don't intend to make any to the form at this point.
