### ISSUE TITLE
Validate upstream carrier has a number when search occurs

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#37]
We should check that a number is still available for purchase when we display available numbers to end users if we have not verified the number is available in the last 15 minutes.

Thinking we can expose a loading spinner while these numbers are verified as available, then use javascript to hide the numbers that are not available? That way we are not bottlenecking page load on these queries.

Should we just re-import the NPANXXes that our initial database query returns?

Teli (3 to 6 second response time):
https://apiv1.teleapi.net/dids/list?token=< ourtoken >&search=< npanxx >

FirstCom (400ms to 600ms response time):
Use the DIDInventorySearch endpoint to re-import the NPA-NXX

BulkVS:
[Likely this method?](https://github.com/AccelerateNetworks/NumberSearch/blob/2ba162392056038b8af91d5530230b86658f16b0/BulkVS/BulkVS/BulkVS.cs#L45)

**Comment by uncheckederror** [comment]
Currently when an order is submitted for purchase we verify that the numbers in the cart are still available before purchasing them.

To improve the buyer's confidence I propose that we run this same availability check when they try to add the number to their cart in the first place.

Running partial ingests from the web app probably isn't a good idea because it would mix concerns across applications and could lead to unintended conflicts. But we could invalidate numbers by changing a flag in the database when this process discovers that a number is no longer available.

**Comment by danry25** [comment]
I did not realize we ran an availability check when numbers in a cart are checked out, that is quite good!

**Comment by uncheckederror** [comment]
@danry25 Given that we are running a check before we execute the number purchase are you happy with the current state, or do you want to add additional checks?
