### ISSUE TITLE
[FEATURE] Add Setting up SMS to Email Notifications to ops

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#410]
**What is the problem that this feature solves?**
Dan told me to file this, so the problem this solves is I fill out the task he requested. 

**Describe the solution you'd like**
We'd love to not have to go to the SoapClient to fill out requests to enable sms for a DID and then have to fill out the SMS to Email notifications through SoapClient as well. 

Steps to currently enable SMS to Email Notifications

1) First, click on the SOAPClient here and search for DIDSMSEnable.
2) Put in the Username and Password with the 11 digit phone number, eg 12068588757. This should enable the next endpoint to work within 24 hours.
3) Once that is enabled,  click on the SOAPClient here and search for DIDRouteSMSToEmail.
4) Set the 11 digit phone number, email it should go to and the Username and Password

**Comment by uncheckederror** [comment]
Okay, this is live but I don't have a number to test it with. I will leave that up to you @sewcialite.

**Comment by uncheckederror** [comment]
Per @sewcialite, @danry25 needs to verify that this feature works on the Messaging page in Ops.

**Comment by danry25** [comment]
I tried registering @sewcialite 's number to her work email, and while it shows up correctly in Messaging Users after pressing Refresh Upstream, it does not show correctly in Owned Numbers (still claiming to be routed to EPID 265 rather than the new EPID created by the email registration.

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/7ccb28c1-57a2-4be7-a18c-d9bec6b4ba77)

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/a936a366-8b81-4afe-bb3c-00875036966e)
 Via SOAP querying LongCodeShowRouting shows the new EPID and the email address as well:
 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/8aeeba18-7b8b-4407-b0eb-5daa5a2e2ce6)

**Other Requests**
Could we also query Refresh Upstream for a number after either Register button is pressed or the Reregister button is pressed in the Messaging Users page?

The flavor text for "Register a Phone Number for Messaging to Email Service" should say:
Phone Numbers registered for service using this method will be enabled for SMS service and routed to a new EPID with our upstream vendor. Messaging to email routed numbers will not show up in the list of active users below, they are not registered against sms.callpipe.com but rather against the upstream vendor.
