### ISSUE TITLE
[BUG] Port Status Emails are not sending

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#422]
**What is broken?**
When a phone number we are porting in changes status to FOC or Complete we used to email the client that the port request had a completion date set (FOC), or the port request was now complete, but these emails have not been sending on recent orders like [this](https://ops.acceleratenetworks.com/Home/Emails/a629fe3a-c924-475a-a336-d72f8e8e9717) or [this](https://ops.acceleratenetworks.com/Home/Order/7a6aa3a7-ff64-45ac-b1c7-d621eacbf9c7) and no failed email is logged.

**Comment by uncheckederror** [comment]
@danry25 okay, I think this is fixed. It should generate the porting notification emails along with the priority ingest process now.

**Comment by danry25** [comment]
Will emails about past port requests that received FOC or completed but were not emailed about be sent?

When should I expect to see emails about port requests that obtained FOC or changed to completed status today go out?

**Comment by uncheckederror** [comment]
> Will emails about past port requests that received FOC or completed but were not emailed about be sent?

If they moved all the way to the COMPLETED state then no email will be sent.

> When should I expect to see emails about port requests that obtained FOC or changed to completed status today go out?

The emails started going out on 10/25/2023 11:45:08 PM you can see the email here: https://ops.acceleratenetworks.com/Home/Emails/7751aadd-510d-4fc8-a8b2-e4592cfa627d

And the order it was for here: https://ops.acceleratenetworks.com/Home/Order/7751aadd-510d-4fc8-a8b2-e4592cfa627d

This was triggered because we picked up on the new FOC dates for this order.

**Comment by danry25** [comment]
We have been getting these emails, closing the issue.
