### ISSUE TITLE
[BUG] CurrentSPID is sometimes updated with a blank value

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#429]
**What is broken?**
Occasionally, the CurrentSPID field is updated with a blank CurrentSPID value, resulting in an inaccurate email like "[Ingest] 111 phone numbers changed Service Providers." being sent, warning of 111 numbers having changes, when only 21 of these numbers had a change in state (specifically SPID 7606 changed names to COMCAST IP PHONE, LLC instead of COMCAST PHONE OF WASHINGTON OREGON, LLC - WA)

**To Reproduce**
I am unclear how to reproduce this misbehavior. I have broken down this email in the spreadsheet here:
[111 Ingested Number Changed - Nov 12 2023.xlsx](https://github.com/AccelerateNetworks/NumberSearch/files/13329092/111.Ingested.Number.Changed.-.Nov.12.2023.xlsx)

**Expected behavior**
Only active numbers that have a change in state in their underlying carrier should be shown.

**Comment by uncheckederror** [comment]
The SPID gets updated to a blank value when we receive a valid LEC (called SPIDName internally) value but no SPID value. Here is an example of query to BulkVS that produces a blank SPID but valid SPIDName. We do not want to update the SPIDName without updating the SPID, as this could be misleading: where the old SPID is listed with a new SPIDName.

`{"tn":"13603867702","lrn":"14254744505","ocn":"483E","lata":"674","city":"EVERETT","ratecenter":"EVERETT","province":"WA","jurisdiction":"INTRASTATE","local":"Y","lec":"ONVOY, LLC - WA","lectype":"CLEC","spid":null,"activation":"1668574800","LIDBName":"","LastPorted":"2022-11-16T05:00:00"}`

https://lrn.bulkCNAM.com/?id={**apiKey**}&did=4808852800&ani=4808852800&format=json

> Only active numbers that have a change in state in their underlying carrier should be shown.

This statement is too vague to be actionable. Look at the JSON above, what fields would have to change in the vendor's response to meet your definition of "a change in state"? Right now we update the record when either the queried SPID or the LEC (SPIDName) are different from what we have currently recorded.

> specifically SPID 7606 changed names to COMCAST IP PHONE, LLC instead of COMCAST PHONE OF WASHINGTON OREGON, LLC - WA

This would trigger an update for the values of every number with that SPID, because the LEC (SPIDName) has changed.

**Comment by danry25** [comment]
I have opened a ticket with BulkVS about this issue.
