### ISSUE TITLE
[BUG] Ops Order Typeahead not taking users to the order suggested

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#446]
**What is broken?**
An order is recommended to me in Ops by the typeahead, yet when I click it no order is found

**Expected behavior**
This should take me to order https://ops.acceleratenetworks.com/Home/Order/eb20c270-0113-47b2-a9e9-bb44e9c47bf1

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/222c6335-d293-41af-894f-dee8c95d10b6)

**Comment by uncheckederror** [comment]
This appears to be broken because the & character is getting escaped to "&amp;". 

This bug occurred because we were getting the text out of the HTML element that you clicked on, using it's element.innerHTML property. This property includes any HTML escaping, formatting, and tags. What we really wanted was just the text displayed by this element. Luckily we can get that by using the element.textContent property which is how this bug was resolved. 

You can read more about the options for getting the text out of an HTML element here: https://www.w3schools.com/jsref/prop_node_textcontent.asp

@danry25 this change is live please test and confirm the fix. @dunkeltron I would call this a funny bug.
