### ISSUE TITLE
List all the Phone Numbers we own in the Ops app

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/NumberSearch#75]
We don't have an inventory of all the Phone Numbers that we own.

We need a page in the Ops app that lists all of the Phone Numbers that we own.

Although we can look in each vendor's portal manually this process is slow and error prone.

This is an item from the list of feature requests in #61

**Comment by uncheckederror** [comment]
- [ ] Ingest owned numbers from TeleMessage
- [ ] Ingest owned numbers from BulkVS
- [ ] Ingest owned numbers from FirstPointCom
- [ ] Run LRN checks on each number to verify that the provider hasn't changed.
- [ ] Store these numbers in the database.
- [ ] List the numbers we own in the Ops app.

**Comment by uncheckederror** [comment]
@danry25 You can try out the new page in the Ops app here: https://ops.acceleratenetworks.com/Home/OwnedNumbers

**Comment by danry25** [comment]
This page has most of the requisite data, but the Number Information column has the phone number, vendor &  Date Ingested smooshed together with no separation. Each should be its own column. On the same note, Notes should be its own, editable column rather than being smooshed under the service provider column.

Our goal is to have skinny rows and a column for every relevant data field. I see the OCN is being shown under Service Provider, though I am unsure if this is actually useful for this purpose. We should discuss this column further, I think it is only useful for automated auditing purposes (eg: tracking phone numbers as they are ported in or port away from us).

**Comment by uncheckederror** [comment]
To get all of the numbers we own out of the BulkVS API we'll need to use the DnQueryAll endpoint.

**Comment by uncheckederror** [comment]
@danry25 Please verify that the current build of the Owned Numbers page in the Ops app meets your requirements.
