### ISSUE TITLE
Use OCN Type to determine whether a port request is Wireless or not

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#81]
**Is your feature request related to a problem? Please describe.**
No, my feature request is to simplify the porting form.

**Describe the solution you'd like**
We should query the LRN for all numbers on a port request. If the ocn_type is any of those listed below (per the [TruOps TRA LERG Routing Guide](https://web.archive.org/web/20200913190020/https://trainfo.iconectiv.com/sites/microsites/files/2019-06/LERG_Routing%20Guide%20-%20General%20Info_05_01_18_new_5_31_19.pdf)) then the number is wireless. Otherwise it is not a wireless number.

Wireless Numbers have an ocn_type of:
```
PCS
P RESELLER
Wireless
W RESELLER
```

If some of the numbers on a port request show wireless and others do not, please throw an error saying "It appears (list all wireless numbers here) is wireless, while the other numbers on the order are not. Please submit two separate orders to port these numbers to us! 
 
**Describe alternatives you've considered**
Forcing the submitter to think about minutia that we can automate away.

**Additional context**
On the [FirstPoint/Endstream LRN API](http://www.endstream.com/endstreamws/OCNLATAdip.asmx?op=RequestOCNLATA), the field is named Ocntype.

**Comment by uncheckederror** [comment]
Rather than rejecting an order based on the ported number wireless or non wireless status after they've already submitted the order and are attempting to add additional porting information, we are instead going to reject the ported number when they first attempt to add it to their cart if the type of the new ported number does not match the ported numbers already in their cart.

**Comment by uncheckederror** [comment]
So the ocn_type field is coming back as "wireless" or "unknown" using the Teli LRNLookup API.
